version: 0.1.0-beta-{build}
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - dev
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: artifacts/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/netcorecontrols/
  api_key:
    secure: 2C4NOeN4awY+fC0FncLK59Ov9Kn/TRfHgn74JWoHMvMfvWE27azJMiadfRfRDiYi
  skip_symbols: true
  on:
    branch: dev