version: 1.0.0-beta1-{build}
configuration:
  - Release
platform: Any CPU
image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
before_build:
  - cmd: dotnet restore
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - dev
  - master
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: artifacts/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/netcorecontrols/
  api_key:
    secure: 2C4NOeN4awY+fC0FncLK59Ov9Kn/TRfHgn74JWoHMvMfvWE27azJMiadfRfRDiYi
  skip_symbols: true
  on:
    branch: master

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /docs.*/