version: 1.0.0-beta1-{build}
configuration:
  - Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - dev
  - master
build_script:  
- ps: .\BuildVS17.ps1
test: off  
artifacts:  
- path: artifacts/*.nupkg
  name: ByteNuts.NetCoreControls
deploy:
- provider: NuGet
  server: https://www.myget.org/F/netcorecontrols/
  api_key:
    secure: 2C4NOeN4awY+fC0FncLK59Ov9Kn/TRfHgn74JWoHMvMfvWE27azJMiadfRfRDiYi
  skip_symbols: true
  on:
    branch: master
